name: project2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.12.0
  google_sign_in: ^6.2.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  webview_flutter: ^4.13.0
  http: ^1.2.0
  flutter_local_notifications: ^17.0.0
  video_player: ^2.9.2  

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"  # warna background
  adaptive_icon_foreground: "assets/images/app_icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/