name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🏗️ Build APK (Split Per ABI)
        run: flutter build apk --release --target lib/main.dart --split-per-abi

      - name: 📤 Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: 📢 Notify Telegram (Success)
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Build APK berhasil untuk commit ${{ github.sha }}"

      - name: ❌ Notify Telegram (Failed)
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ Build gagal di workflow GitHub Actions"

      - name: 📤 Send APK to Telegram
        if: success()
        run: |
          RESPONSE=$(curl -w "\nHTTP_STATUS:%{http_code}" -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F document=@build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
          -F caption="📦 APK (arm64) terbaru berhasil di-build 🚀")
          
          echo "$RESPONSE"
          
          # Jika gagal (HTTP Status bukan 200), gagalkan juga step ini
          if [[ "$RESPONSE" != *"HTTP_STATUS:200"* ]]; then
            echo "Gagal mengirim APK ke Telegram!"
            exit 1
          fi