name: Flutter CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java (Required for Firebase & Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
          cache: true

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 📱 Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter test integration_test/app_test.dart

      - name: 🏗️ Build APK (Release)
        run: flutter build apk --release --flavor prod --target-platform android-arm64

      - name: 🏗️ Build AAB (Play Store)
        run: flutter build appbundle --release --flavor prod

      - name: 🚀 Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-prod-release.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: 📤 Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            build/app/outputs/flutter-apk/app-prod-release.apk
            build/app/outputs/bundle/prodRelease/app-prod-release.aab

      - name: 📢 Telegram Notification
        if: success()
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F document=@build/app/outputs/flutter-apk/app-prod-release.apk \
          -F caption="✅ Build Berhasil! APK & AAB Terbuat. Firebase App Distribution Terupdate! 🚀"